spring:
   application:
    name: sdkserver-server-channel
#spring:
#   cloud:  # 进行SpringCloud的相关配置
#    bus:
#      trace:
#        enabled: true
#   profiles: dev
#   application:
#    name: sdkserver-server-channel
#   datasource:
#    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
#    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
#    url: jdbc:mysql://172.16.20.140:3307/mlsdk?characterEncoding=utf8&useSSL=true   # 数据库名称
#    username: root
#    password: root
#    dbcp2:
#      min-idle: 5                                           # 数据库连接池的最小维持连接数
#      initial-size: 5                                       # 初始化连接数
#      max-total: 5                                          # 最大连接数
#      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
#  rabbitmq:
#     host: 192.168.23.129
#     port: 5672
#     username: guest
#     password: guest

#  config 服务上的配置文件
#spring:
#  profiles:
#    active:
#      -dev
#---
#server:
#  port: 9001
#
#
#mybatis:
#  config-location: classpath:mybatis/mybatis.cfg.xml      # mybatis配置文件所在路径
#  type-aliases-package: com.sdkserver.channel.model    # 所有Entity别名类所在包
#  mapper-locations:
#  - classpath:mybatis/mapper/*.xml                       # mapper映射文件
#
#spring:
#   profiles: dev
#   application:
#    name: sdkserver-server-channel
#   datasource:
#    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
#    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
#    url: jdbc:mysql://172.16.20.140:3307/mlsdk?characterEncoding=utf8&useSSL=true   # 数据库名称
#    username: root
#    password: root
#    dbcp2:
#      min-idle: 5                                           # 数据库连接池的最小维持连接数
#      initial-size: 5                                       # 初始化连接数
#      max-total: 5                                          # 最大连接数
#      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
#
#eureka:
#  client: #客户端注册进eureka服务列表内
#    service-url:
# #     defaultZone: http://localhost:7001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
#  instance:
#    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
#    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
#    instance-id: sdkserver-server-channel
#    prefer-ip-address: true     #访问路径可以显示IP地址
#
#sdkserver-server-game-id: http://172.16.20.140:8001
#
#define:
#  id:
#    game: CHANNEL_ID  #用于Redis生成ID
#
#info:
#  app.name: sdkserver-server-channel
#  company.name: www.miaoleyouxi.com
#  build.artifactId: $project.artifactId$
#  build.version: $project.version$
#---
#server:
#  port: 9001
#
#
#mybatis:
#  config-location: classpath:mybatis/mybatis.cfg.xml      # mybatis配置文件所在路径
#  type-aliases-package: com.sdkserver.channel.model    # 所有Entity别名类所在包
#  mapper-locations:
#  - classpath:mybatis/mapper/*.xml                       # mapper映射文件
#
#spring:
#   profiles: official
#   application:
#    name: sdkserver-server-channel
#   datasource:
#    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
#    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
#    url: jdbc:mysql://172.16.20.140:3307/mlsdk?characterEncoding=utf8&useSSL=true   # 数据库名称
#    username: root
#    password: root
#    dbcp2:
#      min-idle: 5                                           # 数据库连接池的最小维持连接数
#      initial-size: 5                                       # 初始化连接数
#      max-total: 5                                          # 最大连接数
#      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
#
#eureka:
#  client: #客户端注册进eureka服务列表内
#    service-url:
# #     defaultZone: http://localhost:7001/eureka
#      defaultZone: http://172.16.20.140:7001/eureka/,http://172.16.20.140:7002/eureka/,http://172.16.20.140:7003/eureka/
#  instance:
#    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
#    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
#    instance-id: sdkserver-server-channel
#    prefer-ip-address: true     #访问路径可以显示IP地址
#
#sdkserver-server-game-id: http://172.16.20.140:8001
#
#define:
#  id:
#    game: CHANNEL_ID  #用于Redis生成ID
#
#info:
#  app.name: sdkserver-server-channel
#  company.name: www.miaoleyouxi.com
#  build.artifactId: $project.artifactId$
#  build.version: $project.version$
#---
#server:
#  port: 9001
#
#
#mybatis:
#  config-location: classpath:mybatis/mybatis.cfg.xml      # mybatis配置文件所在路径
#  type-aliases-package: com.sdkserver.channel.model    # 所有Entity别名类所在包
#  mapper-locations:
#  - classpath:mybatis/mapper/*.xml                       # mapper映射文件
#
#spring:
#   profiles: test
#   application:
#    name: sdkserver-server-channel
#   datasource:
#    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
#    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
#    url: jdbc:mysql://172.16.20.140:3307/mlsdk?characterEncoding=utf8&useSSL=true   # 数据库名称
#    username: root
#    password: root
#    dbcp2:
#      min-idle: 5                                           # 数据库连接池的最小维持连接数
#      initial-size: 5                                       # 初始化连接数
#      max-total: 5                                          # 最大连接数
#      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
#
#eureka:
#  client: #客户端注册进eureka服务列表内
#    service-url:
# #     defaultZone: http://localhost:7001/eureka
#      defaultZone: http://172.16.20.140:7001/eureka/,http://172.16.20.140:7002/eureka/,http://172.16.20.140:7003/eureka/
#  instance:
#    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
#    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
#    instance-id: sdkserver-server-channel
#    prefer-ip-address: true     #访问路径可以显示IP地址
#
#sdkserver-server-game-id: http://172.16.20.140:8001
#
#define:
#  id:
#    game: CHANNEL_ID  #用于Redis生成ID
#
#info:
#  app.name: sdkserver-server-channel
#  company.name: www.miaoleyouxi.com
#  build.artifactId: $project.artifactId$
#  build.version: $project.version$


#server:
#  port: 9001
#
#
#mybatis:
#  config-location: classpath:mybatis/mybatis.cfg.xml      # mybatis配置文件所在路径
#  type-aliases-package: com.sdkserver.channel.model    # 所有Entity别名类所在包
#  mapper-locations:
#  - classpath:mybatis/mapper/*.xml                       # mapper映射文件
#
#spring:
#   application:
#    name: sdkserver-channel
#   datasource:
#    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
#    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
#    url: jdbc:mysql://172.16.20.140:3307/mlsdk?characterEncoding=utf8&useSSL=true   # 数据库名称
#    username: root
#    password: root
#    dbcp2:
#      min-idle: 5                                           # 数据库连接池的最小维持连接数
#      initial-size: 5                                       # 初始化连接数
#      max-total: 5                                          # 最大连接数
#      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
#
#eureka:
#  client: #客户端注册进eureka服务列表内
#    service-url:
# #     defaultZone: http://localhost:7001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
#  instance:
#    instance-id: sdkserver-channel-9001
#    prefer-ip-address: true     #访问路径可以显示IP地址
#
#define:
#  id:
#    game: CHANNEL_ID  #用于Redis生成ID
#
#info:
#  app.name: sdkserver-server-channel
#  company.name: www.miaoleyouxi.com
#  build.artifactId: $project.artifactId$
#  build.version: $project.version$